# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provision :shell, inline: "sudo locale-gen en_IE.UTF-8"

  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "kafka-formula"
  config.vm.synced_folder "../../kafka", "/srv/formulas/kafka"
  config.vm.synced_folder "../salt", "/srv/salt"
  config.vm.synced_folder "../pillar", "/srv/pillar/"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "kafka-formula"
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: "sudo apt-get install -y python-git"

  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_config = "conf/minion"
    salt.run_highstate = true
  end
end
